services:
  djangoapp_psql:
    container_name: djangoapp_psql
    restart: unless-stopped
    build:
      context: .
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - ./data/web/static:/data/web/static
      - ./data/web/media:/data/web/media
    env_file:
      - ./.env
    environment:
      - POSTGRES_HOST=psql
    depends_on:
      - psql

# MARCADO COM # PARA PRODUCAO

  psql:
    container_name: psql
    restart: always
    image: postgres:16-alpine
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data/
    env_file:
      - ./.env

volumes:
  static_data:
  media_data:
  postgres_data: