services:
  djangoapp_psql:
    container_name: djangoapp_psql
    restart: unless-stopped
    build:
      context: .
    networks:
      - proxy
      - default
    volumes:
      - ./data/web/static:/data/web/static
      - ./data/web/media:/data/web/media
    env_file:
      - ./.env
    environment:
      - POSTGRES_HOST=psql
    depends_on:
      - psql
    labels:
      - "traefik.enable=true"                                                 
      - "traefik.http.routers.meuapp.rule=Host(`blog.samaramutielli.site`)"             
      - "traefik.http.routers.meuapp.entrypoints=websecure"                    
      - "traefik.http.routers.meuapp.tls.certresolver=leresolver"       
      - "traefik.http.services.blog.loadbalancer.server.port=8000"

  psql:
    container_name: psql
    restart: always
    image: postgres:16-alpine
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data/
    env_file:
      - ./.env

networks:
  proxy:
    external: true                            
