services:
  djangoapp_psql:
    container_name: djangoapp_psql
    restart: unless-stopped
    build:
      context: .
    networks:
      - proxy
      - default
    volumes:
      - ./data/web/static:/data/web/static
      - ./data/web/media:/data/web/media
    env_file:
      - ./.env
    environment:
      - POSTGRES_HOST=psql
    depends_on:
      - psql
    labels:
      - "traefik.enable=true"                                                 
      - "traefik.http.routers.meuapp.rule=Host(`blog.docker.localhost`)"             
      - "traefik.http.routers.meuapp.entrypoints=websecure"                    
      - "traefik.http.routers.prometheus.tls=true"   
      - "traefik.http.services.blog.loadbalancer.server.port=8000"
      - "traefik.http.routers.meuapp.priority=10"
  
  psql:
    container_name: psql
    restart: always
    image: postgres:16-alpine
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  nginx-static:
    container_name: nginx-static
    restart: unless-stopped
    image: nginx:alpine
    networks:
      - proxy
    volumes:
      - ./data/web/static:/data/web/static:ro
      - ./data/web/media:/data/web/media:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.static.rule=Host(`blog.docker.localhost`) && (PathPrefix(`/static/`) || PathPrefix(`/media/`))"
      - "traefik.http.routers.static.entrypoints=websecure"
      - "traefik.http.routers.prometheus.tls=true"
      - "traefik.http.services.static.loadbalancer.server.port=80"
      - "traefik.http.routers.static.priority=20"

networks:
  proxy:
    external: true                         
