services:
  djangoapp_psql:
    container_name: djangoapp_psql
    restart: always
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./djangoapp:/djangoapp
      - static_data:/data/web/static/
      - media_data:/data/web/media/
    env_file:
      - ./.env

volumes:
  static_data:
  media_data: