# Generated by Django 6.0.4 on 2026-04-19 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0004_sitesetup_favicon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetup',
            name='favicon',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='assets/favicons/%Y/%m/'),
        ),
    ]
