# Generated by Django 6.0.4 on 2026-04-21 21:18

import utils.model_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0005_alter_sitesetup_favicon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetup',
            name='favicon',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='assets/favicons/%Y/%m/', validators=[utils.model_validators.validate_png]),
        ),
    ]
