[pytest]
DJANGO_SETTINGS_MODULE = project.settings
python_files = test.py tests.py test_*.py tests_*.py *_test.py *_tests.py
pythonpath = .
addopts = 
    -ra
    -v
    --cov=blog
    --cov-report=html
    --cov-report=term-missing
    

